### PR TITLE
Added default EmailSender and EmailSenderOptions from Sample project

### PR DESCRIPTION
**Pull request by dgenezini**
- Added default EmailSender and EmailSenderOptions;
- Added IServiceCollection extension AddPostalDefaultEmailSender;
- Added SendAsync(IEmailSender emailSender) to Email class;

### CODE REVIEW

**Comment by dgenezini** [comment]
PS: Removed the dependency of Microsoft.AspNetCore.Identity.UI.Services.IEmailSender from EmailSender interface, it was not needed.

**Comment by hermanho** [comment]
The reason of inherent from Microsoft.AspNetCore.Identity.UI.Services.IEmailSender is integrated to Microsoft.AspNetCore.Identity and the suggested practice. Most of them are useless when it is not integrated and you just need the following code
```
MailMessage message = await _emailService.CreateMailMessageAsync(emailData);
```

Ref: https://docs.microsoft.com/en-us/aspnet/core/security/authentication/accconfirm?view=aspnetcore-2.1&tabs=visual-studio#enable-account-confirmation-and-password-recovery

**Comment by dgenezini** [comment]
Yes, but it only makes sense if using identity, it doesn't make sense to add this dependency to postal. That's why I removed it.
If using identity, it's just inherit from Postal.EmailSender implementing Microsoft.AspNetCore.Identity.UI.Services.IEmailSender.

**Comment by hermanho** [comment]
The class is just an example to integrate "Identity" in sample repo. After you remove the dependency, it is just that a bridge for SmtpClient which it is same as another class EmailService.

**Pull request closed without merging**
